### ISSUE TITLE
Matrix3 / 4 multiplier order

### ISSUE THREAD

**Issue by naan** [nicklockwood/VectorMath#11]
Correct me if I'm wrong or midunderstangind something, but I think the order of matrix multiplication of VectorMath library seems reversed.

```swift
    public static func *(lhs: Matrix3, rhs: Matrix3) -> Matrix3 {
        
        return Matrix3(
            lhs.m11 * rhs.m11 + lhs.m21 * rhs.m12 + lhs.m31 * rhs.m13,
            .....
    }

    public static func *(lhs: Matrix4, rhs: Matrix4) -> Matrix4 {
        
        var m = Matrix4.identity
        
        m.m11 = lhs.m11 * rhs.m11 + lhs.m21 * rhs.m12
        m.m11 += lhs.m31 * rhs.m13 + lhs.m41 * rhs.m14
       ....
    }
```

According to [this](https://en.wikipedia.org/wiki/Matrix_multiplication#Matrix_product_.28two_matrices.29), algorithm of two matrices is something like this:

<img width="205" alt="screen shot 2017-03-13 at 9 22 22 pm" src="https://cloud.githubusercontent.com/assets/63257/23885835/5284f500-0833-11e7-8b68-64ccbf64fc12.png">

where I believe VectorMath's `*` operator represents `AB`in this equation. (meaning you can write `A * B` in swift to do same calculation.) If so, the function's `lhs` and `rhs` is reversed and since Matrix multiplication is not commutative, it'll produce different results.

I did write a simple Matrix4 <-> CATransform3D conversion code and check something like this:

```
    let m1 = Matrix4( /* init with some values */)
    let m2 = Matrix4( /* init with some other values */)

    let con1 = CATransform3DConcat(CATransform3D(m1), CATransform3D(m2) )
    let con2 = m1 * m2
    XCTAssertTrue(Matrix4(con1) == con2)  // this should pass, but fails

    let con3 = m2 * m1
    XCTAssertFalse(Matrix4(con1) == con3)  // this should pass, but fails

```
Here's what `CATransform3DConcat`s [document](https://developer.apple.com/reference/quartzcore/1436554-catransform3dconcat) says:

> Concatenate 'b' to 'a' and return the result: t' = a * b.

I think it would be better to have reversed order for those methods.

**Comment by naan** [comment]
Sorry, I think I misunderstood this. If you want to keep apply transform, order of function parameter is better, like those cases:

```swift
let m = Matrix4(rotation: ....)
let t = Matrix4(translation: ...)
let s = Matrix4(scale: ...)
let result = t * r * s
```

Just a bit confusing when you communicate with `CATransform3D`.

**Comment by nicklockwood** [comment]
Yeah CATransform works the opposite way round to what you'd expect. I think that's because it's view-centric or something, so it transforms objects from the PoV of the camera rather than the layer's own coordinate space.
