### ISSUE TITLE
Quaternion <-> Euler angle converting back and forth does not return original value

### ISSUE THREAD

**Issue by DJBen** [nicklockwood/VectorMath#13]
Insert the following testing code to `testEulerConversion` test case and observe it to fail

    let quat2 = Quaternion(pitch: 0.12334412, yaw: 1.3521468, roll: -0.53435323)
    let (pitch, yaw, roll) = quat2.toPitchYawRoll()
    let quat2Ref = Quaternion(pitch: pitch, yaw: yaw, roll: roll)
    XCTAssertTrue(quat2 ~= quat2Ref)

**Comment by nicklockwood** [comment]
Fixed in 0.3.1
