### ISSUE TITLE
Make extensions public

### ISSUE THREAD

**Issue by timprepscius** [nicklockwood/VectorMath#15]
put the "public" keyword before the extension declarations, so that they export properly from bundle to bundle/app

example:

```
public extension SCNVector3 {
    init(_ v: Vector3) {
        self.init(x: SCNFloat(v.x), y: SCNFloat(v.y), z: SCNFloat(v.z))
    }
}
```

**Comment by milpitas** [comment]
I've submitted a pull request to address this issue:
https://github.com/nicklockwood/VectorMath/pull/16

Please excuse the chatty commit messages I inadvertently caused above. 
: - )

**Comment by nicklockwood** [comment]
Don't worry, I've squashed the commits :-)

**Comment by milpitas** [comment]
Thanks for writing this awesome library, Nick!

**Comment by nicklockwood** [comment]
👍
