### ISSUE TITLE
Won't compile to Swift's new version

### ISSUE THREAD

**Issue by lfarah** [nicklockwood/VectorMath#6]
<img width="438" alt="screen shot 2016-05-02 at 12 45 30 pm" src="https://cloud.githubusercontent.com/assets/6511079/14965729/cb2d42be-1063-11e6-8edd-2eeeb620487d.png">

**Comment by billhsu** [comment]
@lfarah actually you don't need to include the unit tests in your project. The main file(https://github.com/nicklockwood/VectorMath/blob/master/VectorMath/VectorMath.swift) works well with the latest swift.

**Comment by billhsu** [comment]
@lfarah it's fixed in this PR: #7

**Comment by nicklockwood** [comment]
Fixed in 0.2

**Comment by lfarah** [comment]
Awesome!
