### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by lfarah** [nicklockwood/VectorMath#9]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by nicklockwood** [comment]
This is a bit fiddly due to the optional SceneKit and Quartz extensions. If you feel like adding it as a pull request, I'll take a look.

**Comment by nicklockwood** [comment]
Implemented in 0.3.1
